next-20090730 lguest build breaks with pfn_pmd()
Hi Rusty,

	next-20090729 allmodconfig build breaks at

drivers/lguest/page_tables.c: In function 'setup_pagetables':
drivers/lguest/page_tables.c:987: error: incompatible type for argument 2 of 'pfn_pmd'
drivers/lguest/page_tables.c:994: error: expected ';' before ')' token
drivers/lguest/page_tables.c:994: error: expected statement before ')' token
make[2]: *** [drivers/lguest/page_tables.o] Error 1

build failure is introduced by commit e07dd6220a4bf81a2549e7e37523a2557547d9d7
I have tested the patch for the build failure only.

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
--
 drivers/lguest/page_tables.c |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>