V4L/DVB (13824): mantis: ir_input_register no has 3 arguments
drivers/media/dvb/mantis/mantis_input.c: In function
‘mantis_input_init’:
drivers/media/dvb/mantis/mantis_input.c:129: error: too few arguments to
function ‘ir_input_register’

This happens due to the recent IR code changes.

Cc: Manu Abraham <abraham.manu@gmail.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>