PM / Suspend: Using TASK_ macros requires sched.h
Today's linux-next build (x86_64 allmodconfig) failed like this:

drivers/base/power/main.c: In function 'device_pm_wait':
drivers/base/power/main.c:218: error: 'TASK_UNINTERRUPTIBLE' undeclared (first use in this function)
drivers/base/power/main.c:218: error: (Each undeclared identifier is reported only once
drivers/base/power/main.c:218: error: for each function it appears in.)
drivers/base/power/main.c:218: error: implicit declaration of function 'schedule'
drivers/base/power/main.c: In function 'dbg_show_time':
drivers/base/power/main.c:514: error: implicit declaration of function 'task_pid_nr'
drivers/base/power/main.c: In function '__device_resume_noirq':
drivers/base/power/main.c:551: error: 'TASK_NORMAL' undeclared (first use in this function)
drivers/base/power/main.c: In function '__device_resume':
drivers/base/power/main.c:713: error: 'TASK_NORMAL' undeclared (first use in this function)
drivers/base/power/main.c: In function '__device_suspend_noirq':
drivers/base/power/main.c:970: error: 'TASK_NORMAL' undeclared (first use in this function)
drivers/base/power/main.c: In function '__device_suspend':
drivers/base/power/main.c:1145: error: 'TASK_NORMAL' undeclared (first use in this function)

Presumably caused by commit d43c36dc6b357fa1806800f18aa30123c747a6d1
("headers: remove sched.h from interrupt.h") from Linus' tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Rafael J. Wysocki <rjw@sisk.pl>