ia64: Work around tool-chain bug
I'm getting weird linker failures in the ia64 build:

 : undefined reference to `__ia64_save_stack_nonlocal'
 arch/ia64/kernel/built-in.o(.text+0x11862): In function `pfm_context_create':
 : undefined reference to `__ia64_save_stack_nonlocal'
 arch/ia64/kernel/built-in.o(.text+0x19f52): In function `sys_perfmonctl':
 : undefined reference to `__ia64_save_stack_nonlocal'
 arch/ia64/kernel/built-in.o(.text+0x35942): In function `dup_state_stack':
 : undefined reference to `__ia64_save_stack_nonlocal'
 arch/ia64/kernel/built-in.o(.text+0x35e72): In function `desc_prologue':
 : undefined reference to `__ia64_save_stack_nonlocal'
 arch/ia64/kernel/built-in.o(.text+0x38622): more undefined references to `__ia64_save_stack_nonlocal' follow

Using:

  gcc version 3.4.1 20040815 (Red Hat 3.4.1-9)

... and since i'm unable to build a working cross-compiler
from x86 to ia64 (tried gcc 4.1, 4.2, 4.3, 4.4 and trunk)
lets work it around in a crude way.

NOT-Signed-off-by: Ingo Molnar <mingo@elte.hu>