block, fuse: Fix build error in fs/fuse/dev.c
Today's upstream tree build (x86, 64-bit, allnoconfig+CONFIG_FUSE)
failed with this build error:

  fs/fuse/dev.c: In function ‘request_end’:
  fs/fuse/dev.c:290: error: ‘BLK_RW_SYNC’ undeclared (first use in this function)
  fs/fuse/dev.c:290: error: (Each undeclared identifier is reported only once
  fs/fuse/dev.c:290: error: for each function it appears in.)
  fs/fuse/dev.c:291: error: ‘BLK_RW_ASYNC’ undeclared (first use in this function)

Due to commit:

  8aa7e84: Fix congestion_wait() sync/async vs read/write confusion

Creating a dependency of BDI callbacks on the BLK_RW_* constants,
while those constants are only defined if CONFIG_BLOCK is enabled.

Fix it the simplest way for now, by moving the definitions early
in blkdev.h (this cannot break anything), but the real fix would
be to split up blkdev.h into blkdev-types.h and blkdev-api.h and
make only the API definitions/declarations dependent on
 CONFIG_BLOCK.

Cc: Jens Axboe <jens.axboe@oracle.com>
Cc: Miklos Szeredi <mszeredi@suse.cz>
Signed-off-by: Ingo Molnar <mingo@elte.hu>