xen/xenbus: Disallow it being a module.
We cannot allow the XenBus backend to be a module b/c there
are other modules that depend on the functions exported
via XenBus backend.

Fixes:

ERROR: "xenbus_dev_is_online" [drivers/xen/pciback/xen-pciback.ko] undefined!
ERROR: "__xenbus_register_backend" [drivers/xen/pciback/xen-pciback.ko] undefined!

Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>