Revert "ACPI throttling: Use this_cpu_has and simplify code"
This reverts commit 630c6a2603a844b3771f007224e22db8cc16a038.

b/c the build isn't ready for it yet:

drivers/acpi/processor_throttling.c: In function
‘acpi_throttling_rdmsr’:
drivers/acpi/processor_throttling.c:672: error: implicit declaration of
function ‘this_cpu_has’