drm/ttm: really fix build on architectures without AGP
After commit 1e8655f87333def92bb8215b423adc65403b08a5
("drm/ttm: Fix build on architectures without AGP") was merged, linux-next
got this build failure for a powerpc allyesconfig build:

drivers/gpu/drm/ttm/ttm_page_alloc.c: In function 'set_pages_a
rray_wb':
drivers/gpu/drm/ttm/ttm_page_alloc.c:227: error: implicit declaration of function 'unmap_page_from_agp'
drivers/gpu/drm/ttm/ttm_page_alloc.c: In function 'set_pages_array_wc':
drivers/gpu/drm/ttm/ttm_page_alloc.c:238: error: implicit declaration of function 'map_page_into_agp'

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>