PCI: make PME support dependent on ACPI
In file included from drivers/pci/pcie/pme/pcie_pme.c:22:
include/linux/pci-acpi.h:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'acpi_find_root_bridge_handle'

This file was added in commit f3adb5a4f2e1dfdf9482af05481d0928a39477e8
("PCI PM: PCIe PME root port service driver") from the pci tree and seems
to depend on ACPI.  Maybe its building should depend on CONFIG_ACPI?

I added the following patch for today (I presume there is a better fix):

Acked-by: "Rafael J. Wysocki" <rjw@sisk.pl>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Jesse Barnes <jbarnes@virtuousgeek.org>