ppc64 sys_ipc breakage in 2.6.34-rc2
On Mon, 22 Mar 2010, Andreas Schwab wrote:
>
> ipc/syscall.c:17: error: conflicting types for ‘sys_ipc’
> include/linux/syscalls.h:691: note: previous declaration of ‘sys_ipc’ was here

Hmm. Right you are. Why don't I see this? (I already applied the patch)

Ahh. Because this only triggers with __ARCH_WANT_SYS_IPC. But why didn't
Anton see it then?

Anyway, I assume the following fixes it. Can you verify?

		Linus