Revert "Input: libps2 - additional locking for i8042 ports"
This reverts commit 181d683d752c432635eda0f182ee71548c1f1820.

causes build error:

drivers/built-in.o: In function `ps2_end_command':
(.text+0x17c941): undefined reference to `i8042_check_port_owner'
drivers/built-in.o: In function `ps2_end_command':
(.text+0x17c94a): undefined reference to `i8042_unlock_chip'
drivers/built-in.o: In function `ps2_begin_command':
(.text+0x17c98a): undefined reference to `i8042_check_port_owner'
drivers/built-in.o: In function `ps2_begin_command':
(.text+0x17c993): undefined reference to `i8042_lock_chip'

Signed-off-by: Ingo Molnar <mingo@elte.hu>