signal.h need a definition of struct task_struct
fixes these build errors on powerpc:

In file included from arch/powerpc/mm/fault.c:18:
include/linux/signal.h:239: error: 'struct task_struct' declared inside parameter list
include/linux/signal.h:239: error: its scope is only this definition or declaration, which is probably not what you want
include/linux/signal.h:240: error: 'struct task_struct' declared inside parameter list
include/linux/signal.h:241: error: 'struct task_struct' declared inside parameter list
include/linux/signal.h:250: error: 'struct task_struct' declared inside parameter list
include/linux/signal.h:254: error: 'struct task_struct' declared inside parameter list
cc1: warnings being treated as errors

Exposed by commit e66eed651fd1 ("list: remove prefetching from regular
list iterators").

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>