Fix put_cpu_var() invocation on user_return_notifier code
Today's linux-next build (x86_64 allmodconfig) failed like this:

kernel/user-return-notifier.c: In function 'fire_user_return_notifiers':
kernel/user-return-notifier.c:45: error: expected expression before ')' token

Introduced by commit 7c68af6e32c73992bad24107311f3433c89016e2 ("core,
x86: Add user return notifiers") from the tip and kvm trees but revealed
by commit e0fdb0e050eae331046385643618f12452aa7e73 ("percpu: add __percpu
for sparse") from the percpu tree.  Before that percpu tree commit,
"put_cpu_var()" would compile without error (even though it really needs
a parameter).

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Avi Kivity <avi@redhat.com>