linux-next: drbd tree build failure
Today's linux-next build (x86_64 allmodconfig) failed like this:

drivers/block/drbd/drbd_nl.c: In function 'drbd_setup_queue_param':
drivers/block/drbd/drbd_nl.c:707: error: implicit declaration of function 'blk_queue_stack_limits'

Caused by commit 6dc986e736ca1e76a45d025a920f3a66855fc2aa ("block:
Deprecate blk_queue_stack_limits") from the block tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Philipp Reisner <philipp.reisner@linbit.com>