USB sierra: Fix build if !CONFIG_PM
This build failure:

  drivers/usb/serial/sierra.c: In function 'sierra_suspend':
  drivers/usb/serial/sierra.c:936: error: 'struct usb_device' has no member named 'auto_pm'

Triggers because the ->auto_pm functionality depends on CONFIG_PM.

Signed-off-by: Ingo Molnar <mingo@elte.hu>