drm: Fix build failure in radeon and i915 drivers
this build failure:

drivers/built-in.o: In function `drm_irq_uninstall':
(.text+0xb719e): undefined reference to `vga_client_register'
drivers/built-in.o: In function `drm_irq_install':
(.text+0xb7309): undefined reference to `vga_client_register'
drivers/built-in.o: In function `radeon_device_fini':
(.text+0xe400f): undefined reference to `vga_client_register'
drivers/built-in.o: In function `radeon_device_init':
(.text+0xe455b): undefined reference to `vga_client_register'

got introduced with upstream merge 44040f1.

At first sight it appears to be due to CONFIG_DRM_RADEON relying on
VGA_ARB facilities but this is not expressed in the Kconfig rules.

drm_irq.o relies on it too - so the whole DRM facilities relies
on VGA_ARB. I've added a select to express this dependency.

VGA_ARB is not a simple option, it depends on PCI, so in theory
select is not safe - but this is a special case since DRM itself
depends on PCI too.

Cc: torvalds@linux-foundation.org
Cc: dri-devel@lists.sf.net
Cc: Dave Airlie <airlied@linux.ie>
LKML-Reference: <20090921161207.GA9741@elte.hu>
Signed-off-by: Ingo Molnar <mingo@elte.hu>