microblaze: Add missing header to prom.h
of_serial and physmap_of require of_address_to_resource.

CC      drivers/serial/of_serial.o
drivers/serial/of_serial.c: In function 'of_platform_serial_setup':
drivers/serial/of_serial.c:47: error: implicit declaration of function 'of_address_to_resource'
make[5]: *** [drivers/serial/of_serial.o] Error 1

CC      drivers/mtd/maps/physmap_of.o
drivers/mtd/maps/physmap_of.c: In function 'of_flash_probe':
drivers/mtd/maps/physmap_of.c:268: error: implicit declaration of function 'of_address_to_resource'
make[6]: *** [drivers/mtd/maps/physmap_of.o] Error 1
make[5]: *** [drivers/mtd/maps] Error 2
make[4]: *** [drivers/mtd] Error 2
make[3]: *** [drivers] Error 2

Signed-off-by: Michal Simek <monstr@monstr.eu>
CC: Grant Likely <grant.likely@secretlab.ca>