Fix compile error in mm/slab.c
Commit f385db6d4 (MM: Kmemsize accounting bits) introduced a syntax
error into mm/slab.c:

  CC      mm/slab.o
  mm/slab.c: In function 'alloc_slabmgmt':
  mm/slab.c:2687: error: too few arguments to function 'kmem_cache_alloc_node
  mm/slab.c:2687: warning: left-hand operand of comma expression has no effec
  mm/slab.c:2687: warning: statement with no effect
  mm/slab.c:2687: error: expected ';' before ')' token
  mm/slab.c:2687: error: expected statement before ')' token
  make[1]: *** [mm/slab.o] Error 1
  make: *** [mm] Error 2

http://bugzilla.openvz.org/show_bug.cgi?id=1486

Signed-off-by: Sven-Haegar Koch <mail-openvz@sdinet.de>
Signed-off-by: Pavel Emelyanov <xemul@openvz.org>