nvram: Fix missing smp_lock.h in nvram
The bkl has been removed from nvram_llseek() and smp_lock.h was
removed because another patch in the same tree zapped the remaining
usage of bkl in the same file. But this patch must have been excluded
later, then we still need the smp_lock.h headers for the bkl use
in nvram_open().

This fixes the following build error:

drivers/char/nvram.c: In function nvram_open:
drivers/char/nvram.c:332: erreur: implicit declaration of function lock_kernel
drivers/char/nvram.c:339: erreur: implicit declaration of function
unlock_kernel
make[2]: *** [drivers/char/nvram.o] Erreur 1
make[1]: *** [drivers/char] Erreur 2
make: *** [drivers] Erreur 2

Signed-off-by: Frederic Weisbecker <fweisbec@gmail.com>