kmsg: Fix parameter limitations
 The kmsg infrastructure, currently only employed on s/390, has limitations
 with the parameters it can handle due to the way it assembles the
 magic string for parsing with scripts/kmsg-doc.

 cpp expects the result to be a valid expression and exits with an error
 if it is not.

 The netfilter ipvs code causes this error, though there are more examples:
 error: pasting "_ARGS_" and "&" does not give a valid preprocessing token

 This stems from an otherwise valid expression:
 pr_info("Registered protocols (%s)\n", &protocols[2]);

 It tries to concatenate _ARGS_ and &protocols[2] and fails.

 This patch fixes the issue by stringifying the entire parameter list
 and allowing kmsg-doc to unquote the resultant expression.

 The dev_* expressions that evaluate to __KMSG_DEV are unaffected because
 the insertion of the "dev, " between _ARGS_ and the parameter list ends
 up creating a valid expression.

Signed-off-by: Jeff Mahoney <jeffm@suse.com>