xen/pci: Fix compile errors.
In the past we used to have much more of the CONFIG_XEN_*. We have
trimmed them down (yeey), but forgot to move around one of the header
files. This also fixes:

linux-next-20101214/arch/x86/pci/xen.c:451: error: redefinition of 'xen_find_device_domain_owner'
linux-next-20101214/arch/x86/include/asm/xen/pci.h:25: note: previous definition of 'xen_find_device_domain_owner' was here
linux-next-20101214/arch/x86/pci/xen.c:465: error: redefinition of 'xen_register_device_domain_owner'
linux-next-20101214/arch/x86/include/asm/xen/pci.h:29: note: previous definition of 'xen_register_device_domain_owner' was here
linux-next-20101214/arch/x86/pci/xen.c:487: error: redefinition of 'xen_unregister_device_domain_owner'
linux-next-20101214/arch/x86/include/asm/xen/pci.h:34: note: previous definition of 'xen_unregister_device_domain_owner' was here

Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
Reported-by: Randy Dunlap <randy.dunlap@oracle.com>