linux-next: 20090926 - drop autoconf.h from DRBD driver
Hi Sam,

	next-20090926 allyesconfig build breaks on powerpc,

drivers/block/drbd/drbd_proc.c:26:28: error: linux/autoconf.h: No such file or directory
make[3]: *** [drivers/block/drbd/drbd_proc.o] Error 1

dropping autoconf.h from drbd_proc.c helps. The cleanup patch drops the
unneeded include autoconf.h.

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
Acked-by: Sam Ravnborg <sam@ravnborg.org>
--
 drivers/block/drbd/drbd_main.c     |    1 -
 drivers/block/drbd/drbd_nl.c       |    1 -
 drivers/block/drbd/drbd_proc.c     |    1 -
 drivers/block/drbd/drbd_receiver.c |    1 -
 drivers/block/drbd/drbd_req.c      |    1 -
 drivers/block/drbd/drbd_req.h      |    1 -
 drivers/block/drbd/drbd_worker.c   |    1 -
 drivers/staging/cowloop/cowloop.c  |    4 ----
 drivers/staging/iio/ring_sw.h      |    1 -
 9 files changed, 0 insertions(+), 12 deletions(-)