mm: include prefetch.h
Commit e66eed651fd1 ("list: remove prefetching from regular list
iterators") removed the include of prefetch.h from list.h, so include
it explicitly.

Fixes thids build error on sparc32:

mm/slab.c: In function '__cache_alloc':
mm/slab.c:3493: error: implicit declaration of function 'prefetchw'

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>