thinkpad-acpi: Fix build on !CONFIG_THINKPAD_ACPI_HOTKEY_POLL
This build error:

  drivers/platform/x86/thinkpad_acpi.c: In function 'tpacpi_hotkey_driver_mask_set':
  drivers/platform/x86/thinkpad_acpi.c:2238: error: lvalue required as left operand of assignment

Triggers because in the !CONFIG_THINKPAD_ACPI_HOTKEY_POLL case
tpacpi_hotkey_driver_mask_set ymbol is defined to a constant
literal - which is not an lvalue so cannot be assigned to.

The whole tpacpi_hotkey_driver_mask_set() function is not used
in the !CONFIG_THINKPAD_ACPI_HOTKEY_POLL, so enclose it with
an #ifdef.

Signed-off-by: Ingo Molnar <mingo@elte.hu>