AMD64 EDAC: Fix build
-tip testing found this build failure:

drivers/edac/edac_mce_amd.c: In function ‘decode_mce’:
drivers/edac/edac_mce_amd.c:408: error: ‘per_cpu__cpu_llc_id’ undeclared (first use in this function)
drivers/edac/edac_mce_amd.c:408: error: (Each undeclared identifier is reported only once
drivers/edac/edac_mce_amd.c:408: error: for each function it appears in.)

I did the patchlet below but this needs a cleaner fix eventually. A
proper node abstraction needs to be factored out and provided as a
facility regardless of config settings.

Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Doug Thompson <norsk5@yahoo.com>
Cc: Borislav Petkov <borislav.petkov@amd.com>
LKML-Reference: <20090915110940.GA8134@elte.hu>
Signed-off-by: Ingo Molnar <mingo@elte.hu>