PTI: depends on X86 && PCI
Building on ia64 yields this build failure:
drivers/misc/pti.c:657:3: error: implicit declaration of function 'copy_from_user' [-Werror=implicit-function-declaration]

Since the PTI device is specific to the Penwell type of Intel Atom
device, make the driver depend on X86. Further, it uses the PCI
infrastructure and should depend on PCI as well.

Cc: J Freyensee <james_p_freyensee@linux.intel.com>
Signed-off-by: Jeff Mahoney <jeffm@suse.com>