hwlat: depends on RING_BUFFER (build fix)
hwlat_detector build fails because it uses ring_buffer interfaces
without depending on RING_BUFFER.

hwlat_detector.c:(.text+0x8d906): undefined reference to `ring_buffer_reset'
hwlat_detector.c:(.text+0x8d98c): undefined reference to `ring_buffer_free'
hwlat_detector.c:(.text+0x8dd16): undefined reference to `__ring_buffer_alloc'
hwlat_detector.c:(.text+0x8df15): undefined reference to `ring_buffer_free'
hwlat_detector.c:(.text+0x8e100): undefined reference to `ring_buffer_write'
hwlat_detector.c:(.text+0x8e239): undefined reference to `ring_buffer_consume'
hwlat_detector.c:(.text+0x8e2ac): undefined reference to `ring_buffer_event_data'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Jon Masters <jcm@jonmasters.org>