Revert "fanotify: Do check against max_marks and increase number of group marks atomically"
This reverts commit 5876b30fc2c91d67386f91da62b14f159d7bb41f.

This was reverted due to:

Hi Eric,

After merging the fsnotify tree, today's linux-next build (powerpc
ppc64_defconfig) failed like this:

fs/notify/mark.c: In function 'fsnotify_add_mark':
fs/notify/mark.c:230: error: 'struct fsnotify_group' has no member named
'fanotify_data'

Caused by commit 0ed64ab6b338e4269c9f25de83781619ecd624f1 ("fsnotify:
code and error path cleanup in fsnotify_add_mark").  This build has
CONFIG_FANOTIFY not set.

I have used the fsnotify tree from next-20101109 for today.

Conflicts:

	fs/notify/mark.c