V4L/DVB: mantis: depends on IR_CORE
mantis uses ir_input_register so it should depend on IR_CORE.

ERROR: "ir_input_unregister" [drivers/media/dvb/mantis/mantis_core.ko] undefined!
ERROR: "__ir_input_register" [drivers/media/dvb/mantis/mantis_core.ko] undefined!

[mchehab@redhat.com: mingo sent me exactly the same patch. Fold his SOB on this one]
Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>