jbd: export log_start_commit for ext3
Today's linux-next build (x86_64 allmodconfig) failed like this:

ERROR: "log_start_commit" [fs/ext3/ext3.ko] undefined!

Caused by commit fe8bc91c4c30122b357d197117705cfd4fabaf28 ("ext3: Wait
for proper transaction commit on fsync").

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>