Remove bad call to `quicklist_total_size'
Remove bad call to `quicklist_total_size'

This call was introduced by commit
  38ede533da003eb5d131e7adc7152728296c0ae4
as a typo. It was fixed later as the last argument to `sprintf' in
`meminfo_read_proc' by commit
  c303f1d00d2a638b39ca1ae2f9eb0ee04f13b1dc
This will cause an error if you are building with CONFIG_QUICKLIST
disabled. If you are building with CONFIG_QUICKLIST=y, it will cause
only a warning:
  fs/proc/proc_misc.c: In function 'meminfo_read_proc':
  fs/proc/proc_misc.c:283: warning: too many arguments for format

Signed-off-by: Anton Protopopov <aspsk@altlinux.org>
Signed-off-by: Pavel Emelyanov <xemul@openvz.org>