vbus-proxy also uses ioq, so it should select IOQ.
When CONFIG_VBUS_PROXY=[ym] and VBUS_PCIBRIDGE=n:

ERROR: "ioq_init" [drivers/vbus/vbus-proxy.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Gregory Haskins <ghaskins@novell.com>