tracing/branch-tracer: PROFILE_BRANCHES_PER_CPU must depend on SMP
While enabling the per cpu branch tracing in a non SMP config,
we get the following build failure:

kernel/trace/trace_branch.c: In function ‘branch_profiler’:
kernel/trace/trace_branch.c:353: error: implicit declaration of function ‘SHIFT_PERCPU_PTR’
kernel/trace/trace_branch.c:353: error: implicit declaration of function ‘per_cpu_offset’
kernel/trace/trace_branch.c:353: error: invalid type argument of ‘->’ (have ‘int’)
kernel/trace/trace_branch.c: In function ‘calculate_stat’:
kernel/trace/trace_branch.c:364: error: invalid type argument of ‘unary *’ (have ‘int’)
kernel/trace/trace_branch.c:366: error: invalid type argument of ‘->’ (have ‘int’)
kernel/trace/trace_branch.c:367: error: invalid type argument of ‘->’ (have ‘int’)

This is because the branch tracer uses per cpu internals that are not
supported on !CONFIG_SMP case.

To fix it we just need to disable the per cpu branch tracing in
!CONFIG_SMP case.

[ Impact: fix a build failure with the branch tracer ]

Reported-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Frederic Weisbecker <fweisbec@gmail.com>